[12.0][ADD] Report picking summary
OCA/stock-logistics-reporting pull request #178
Opened 2022-01-24 11:10 UTC by quentinDupont

This module adds the possibility to select several Pickings and print a Report summary with two sheets :
* Products Summary (where the total sum is calculated for each product)
* Detail Part (each Picking is shown)

![pdf_report](https://user-images.githubusercontent.com/9005817/100893893-2558ba80-34bc-11eb-997f-2570714f2087.png)

Some options on wizard : 

![image](https://user-images.githubusercontent.com/9005817/100886888-a2803180-34b4-11eb-9fd0-ea7fa700f88f.png)

Migration and improvment of @grap custom module from @legalsylvain : https://github.com/grap/grap-odoo-custom/tree/8.0/grap_qweb_report

2022-01-24 11:18 UTC, legalsylvain approved these changes
Used in production since several monthes.
works like a charm.

code review & test.

Note @quentinDupont : you can add you as the maintainer of the application in the manifest adding the key : ``"maintainers": ["quentinDupont"],``
it will ping you if people want to change code, and you can also apply patches.

2022-02-03 18:00 UTC, rousseldenis requested changes
@quentinDupont Thanks for your contribution.

Code review.

2022-02-03 18:00 UTC, rousseldenis commented on stock_picking_report_summary/models/picking_summary_wizard.py
> +        # product_lines_sorted = sorted(
Could you remove unused comments ?

2022-02-03 18:00 UTC, rousseldenis commented on stock_picking_report_summary/models/picking_summary_wizard.py
> +    print_summary = fields.Boolean(
Could you put fields on top ?

2022-02-03 18:00 UTC, rousseldenis commented on stock_picking_report_summary/models/picking_summary_wizard.py
> +        default=_default_picking_line_qty)
You can change to lambda

2022-02-03 18:00 UTC, rousseldenis commented on stock_picking_report_summary/models/picking_summary_wizard.py
> +    standard_price_total = fields.Float(
I don't think this is common to add price in picking report (e.g.: if it's transmitted to customer as price can vary)

2022-02-03 18:00 UTC, rousseldenis commented on stock_picking_report_summary/reports/report_print_picking_summary_template.xml
> +                                        <span t-esc="round(product_line.standard_price_total,2)"/>
Why 2 ?

2022-03-28 07:43 UTC, rousseldenis commented
@quentinDupont

2022-05-11 09:59 UTC, quentinDupont commented on stock_picking_report_summary/models/picking_summary_wizard.py
> +    standard_price_total = fields.Float(
You're right !
It's now optional on wizard, by default set to False

2022-05-11 09:59 UTC, quentinDupont commented on stock_picking_report_summary/reports/report_print_picking_summary_template.xml
> +                                        <span t-esc="round(product_line.standard_price_total,2)"/>
Rmeove it and handle in fields precision

2022-05-11 10:00 UTC, quentinDupont commented
> @quentinDupont

Thanks for your nice review ! I think i covered all your remarks :)

2022-09-12 07:56 UTC, quentinDupont commented
@rousseldenis I think my last commit covers all your remarks if you can take a look ;)

2022-09-12 08:02 UTC, rousseldenis approved these changes
Seems very good.

2022-09-12 08:22 UTC, legalsylvain approved these changes
Thanks !

2022-09-12 08:41 UTC, rousseldenis commented
@quentinDupont Could you modify your last commit message with something like "[IMP] stock_report_picking_summary: optional print prices" ?

2022-09-12 09:39 UTC, quentinDupont commented
> @quentinDupont Could you modify your last commit message with something like "[IMP] stock_report_picking_summary: optional print prices" ?

Yep, here it is

2022-09-12 10:15 UTC, pedrobaeza commented
Isn't that part the same as https://github.com/OCA/stock-logistics-reporting/tree/12.0/stock_picking_report_valued ?

2022-09-14 10:43 UTC, quentinDupont commented
> Isn't that part the same as https://github.com/OCA/stock-logistics-reporting/tree/12.0/stock_picking_report_valued ?

Hello,
stock_picking_report_valued provides Delivery slip report, kind of a official document, but this new module stock_picking_report_summary is a quick visual summary of what you have to prepare, product by product. then picking by picking. 
In the food industry, it is useful for example to prepare orders, to know quickly the quantity of salads ordered by my x customers, then to distribute these salads in such or such basket (I agree this last part is close to the Delivery slip module).

2022-10-01 14:24 UTC, dreispt commented
/ocabot merge nobump

2022-10-01 15:19 UTC, merged