[FIX] stock_picking_report_valued_sale_mrp: multipicking
OCA/stock-logistics-reporting pull request #179
Opened 2022-02-03 17:08 UTC by chienandalu

When the recordset comes from multiple picking we could get a wrong
calculation of the mrp lines in the report when the conditions of same
component for the same order line would apply. So for every picking we
have to compute the kits valuations independently.

cc @Tecnativa TT34194

ping @victoralmau @pedrobaeza

2022-02-03 20:21 UTC, pedrobaeza requested changes
I miss clear steps to reproduce the problem, for example: do this and that, and you get this problem/error, and if so, reflect such steps in a regression test.

2022-02-03 20:21 UTC, pedrobaeza commented on stock_picking_report_valued_sale_mrp/models/stock_move_line.py
>              # Deduct the kit quantity from the first component in the picking.
```suggestion
            # Deduce the kit quantity from the first component in the picking.
```

2022-02-03 20:21 UTC, pedrobaeza commented on stock_picking_report_valued_sale_mrp/models/stock_move_line.py
> +        if they wen't altogether"""
Not sure if this is what you want to say:

```suggestion
        if they weren't shipped altogether.
        """
```

2022-03-01 14:52 UTC, pedrobaeza commented
@chienandalu can you please add the regression test?

2022-10-11 10:06 UTC, rousseldenis commented
@chienandalu Could you attend @pedrobaeza comments ?

2023-02-21 20:33 UTC, pedrobaeza approved these changes
Let's merge this for not losing the fix:

/ocabot merge patch

2023-02-21 20:37 UTC, merged