[15.0][MIG] stock_move_value_report: Migration to version 15.0
OCA/stock-logistics-reporting pull request #220
Opened 2022-09-02 11:05 UTC by LudLaf

cc @Tecnativa TT38342

2022-09-02 12:17 UTC, pedrobaeza commented
/ocabot migration stock_move_value_report

2022-09-07 18:28 UTC, pedrobaeza requested changes, later dismissed
Please test each report. For example, there's no more `stock.inventory` object.

2022-09-07 18:28 UTC, pedrobaeza commented on stock_move_value_report/README.rst
> +- *Inventory > Transfrers*
```suggestion
- *Inventory > Transfers*
```

2022-09-07 18:28 UTC, pedrobaeza commented on stock_move_value_report/README.rst
> +A pdf preport with the operations linked to these records and their cost will
```suggestion
A pdf report with the operations linked to these records and their cost will
```

2022-10-03 09:09 UTC, LudLaf commented
> Please test each report. For example, there's no more `stock.inventory` object.

All reports have been tested, and the one related to `stock.inventory` has been removed.
Besides, all other requested changes are now fixed.

2022-11-27 20:02 UTC, carlosdauden approved these changes
Code LGTM

2022-12-01 17:23 UTC, sergio-teruel approved these changes

2022-12-01 17:31 UTC, pedrobaeza commented
/ocabot merge nobump

2022-12-01 17:37 UTC, merged