[15.0][MIG] stock_account_quantity_history_location: Migration to version 15.0
OCA/stock-logistics-reporting pull request #268
Opened 2023-03-16 22:44 UTC by ernestotejeda

Cc @Tecnativa TT37317

Depends on:
  - [x] https://github.com/OCA/stock-logistics-reporting/pull/272

2023-03-16 22:55 UTC, ernestotejeda commented
ping @chienandalu

2023-03-17 13:14 UTC, rousseldenis commented
/ocabot migration stock_account_quantity_history_location

2023-03-17 17:13 UTC, chienandalu approved these changes
Great :+1: . A possible (and easy) improvement (also in the main module) would be to add the location filter to the display name: https://github.com/odoo/odoo/blob/15.0/addons/stock_account/wizard/stock_quantity_history.py#L15

2023-03-21 10:07 UTC, ernestotejeda commented
@DavidJForgeFlow could you review it, please?

2023-03-21 10:15 UTC, DavidJForgeFlow approved these changes
It may be good changing all Eficent mentions for ForgeFlow, but other than that it LGTM!

2023-03-21 12:59 UTC, ernestotejeda commented
Changes done @chienandalu @DavidJForgeFlow

2023-03-21 14:37 UTC, chienandalu requested changes
Watch out :warning:  you amended your last changes into the temporal commit `[DON'T MERGE] test-requirements.txt`

2023-03-21 14:37 UTC, chienandalu commented on stock_account_quantity_history_location/wizards/stock_quantity_history.py
> +            action["display_name"] += " ({})".format(self.location_id.complete_name)
```suggestion
            action["display_name"] = f"{self.location_id.complete_name} - {action["display_name"]}"
```

2023-03-21 14:50 UTC, ernestotejeda commented
> Watch out warning you amended your last changes into the temporal commit `[DON'T MERGE] test-requirements.txt`

Right, I didn't realize it, now I fix it

2023-03-21 15:16 UTC, ernestotejeda commented
changes done @chienandalu

2023-03-29 22:47 UTC, pedrobaeza approved these changes
/ocabot merge nobump

2023-03-29 22:57 UTC, merged