Picking XLSX Report
OCA/stock-logistics-reporting pull request #30
Opened 2016-11-25 14:00 UTC by JayVora-SerpentCS

2017-01-27 13:59 UTC, tafaRU requested changes
In addition, please replace Serpent icon by https://github.com/OCA/maintainer-tools/blob/master/template/module/static/description/icon.png

2017-01-27 13:59 UTC, tafaRU commented on stock_picking_report_xlsx/README.rst
> +Bugs are tracked on `GitHub Issues <https://github.com/OCA/stock-logistics-reporting/issues>`_.
Please use up-to-date version.

2017-01-27 13:59 UTC, tafaRU commented on stock_picking_report_xlsx/README.rst
> +- Serpent Consulting Services Pvt. Ltd.<jay.vora@serpentcs.com>
replace - by *

2017-01-27 13:59 UTC, tafaRU commented on stock_picking_report_xlsx/README.rst
> +To contribute to this module, please visit http://odoo-community.org.
s/http/https

2017-01-27 13:59 UTC, tafaRU commented on stock_picking_report_xlsx/__init__.py
> +# © 2016 Serpent Consulting Services Pvt. Ltd
replace © by Copyright

2017-01-27 13:59 UTC, tafaRU commented on stock_picking_report_xlsx/__openerp__.py
> +# © 2016 Serpent Consulting Services Pvt. Ltd
Same as above

2017-01-27 13:59 UTC, tafaRU commented on stock_picking_report_xlsx/__openerp__.py
> +    'version': '8.0.0.1.0',
Use 8.0.1.0.0 instead.

2017-01-27 13:59 UTC, tafaRU commented on stock_picking_report_xlsx/report/__init__.py
> +# © 2016 Serpent Consulting Services Pvt. Ltd
Same as above.

2017-01-27 13:59 UTC, tafaRU commented on stock_picking_report_xlsx/report/__init__.py
> +from . import stock_picking_xlsx_report
no newline at end of file

2017-01-27 13:59 UTC, tafaRU commented on stock_picking_report_xlsx/report/stock_picking_xlsx_report.py
> +# © 2016 Serpent Consulting Services Pvt. Ltd
Same as above.

2017-01-27 13:59 UTC, tafaRU commented on stock_picking_report_xlsx/static/.svn/all-wcprops
> +K 25
Please remove this file.

2017-01-27 13:59 UTC, tafaRU commented on stock_picking_report_xlsx/static/.svn/entries
> +10
Please remove this file.

2017-01-27 13:59 UTC, tafaRU commented on stock_picking_report_xlsx/views/report_view.xml
> +</openerp>
no newline at end of file

2017-02-07 16:11 UTC, tafaRU commented
@JayVora-SerpentCS, thanks a lot!
Could you also please squash commits to only one?

2017-02-13 12:25 UTC, JayVora-SerpentCS commented
Commits Squashed,
Thanks.

2017-02-17 13:29 UTC, tafaRU commented on stock_picking_report_xlsx/__openerp__.py
> +    'author': """Serpent Consulting Services Pvt. Ltd.,
better do not use triple quote here and please also add Agile Business Group.

2017-02-17 13:30 UTC, tafaRU commented on stock_picking_report_xlsx/__openerp__.py
> +    'summary': "Print stock picking report in xlsx",
for consintency it should be better use single quote everywhere, so please put:
`'Print stock picking report in xlsx'`

2017-02-24 14:11 UTC, tafaRU approved these changes
Thanks a lot!

2017-02-24 16:31 UTC, eLBati requested changes

2017-02-24 16:31 UTC, eLBati commented on stock_picking_report_xlsx/README.rst
> +Stock Picking Rerport in XLSX
Rerport -> Report

2017-02-24 16:38 UTC, eLBati commented on stock_picking_report_xlsx/README.rst
> +Stock Picking Rerport in XLSX
Afterwards, :+1:

2017-05-15 11:15 UTC, JayVora-SerpentCS commented
Would someone check please?

2019-06-19 06:36 UTC, rousseldenis commented
@JayVora-SerpentCS At least we can merge. Can you just squash the commits ?

2019-06-19 13:22 UTC, JayVora-SerpentCS commented
Did it, finally! so old PR gets a life!

2019-06-19 13:28 UTC, rousseldenis commented
@eLBati Could you update your review ?

2019-06-19 13:32 UTC, eLBati commented
@JayVora-SerpentCS @rousseldenis too many commits and files changed :thinking:

2019-06-19 13:34 UTC, rousseldenis commented
> @JayVora-SerpentCS @rousseldenis too many commits and files changed

Inded.

@JayVora-SerpentCS Could you fix this and limit changed files to module you want ?

2019-06-19 14:05 UTC, JayVora-SerpentCS commented
I just did upstream as it was too old! I preserved all commits.

2021-11-28 12:19 UTC, closed without merging