[9.0][NEW] stock_move_description_report: New module WIP
OCA/stock-logistics-reporting pull request #32
Opened 2017-02-03 10:37 UTC by carlosdauden

New report to print move description in delivery split.
Forced allways to print from moves instead of operations.

@Tecnativa

2017-02-03 10:54 UTC, pedrobaeza commented
The name should be `stock_picking_report_custom_description`

2017-02-07 21:26 UTC, pedrobaeza requested changes

2017-02-07 21:26 UTC, pedrobaeza commented on stock_picking_report_custom_description/__init__.py
> +import models
`from . import...`

2017-02-07 21:26 UTC, pedrobaeza commented on stock_picking_report_custom_description/__openerp__.py
> +    "category": "Stock",
Isn't `Warehouse` the `stock` module category?

2017-02-07 21:26 UTC, pedrobaeza commented on stock_picking_report_custom_description/__openerp__.py
> +    "summary": "New report to print move description in delivery split",
`Show moves description in picking reports`

2017-02-07 21:26 UTC, pedrobaeza commented on stock_picking_report_custom_description/i18n/es.po
> +#~ msgid "Description"
Why is this here?

2017-02-07 21:26 UTC, pedrobaeza commented on stock_picking_report_custom_description/i18n/es.po
> +msgstr "Operaciones de picking (descripción)"
s/picking/albarán

2017-02-07 21:26 UTC, pedrobaeza commented on stock_picking_report_custom_description/views/report_deliveryslip.xml
> +    <template id="report_delivery_document_description" inherit_id="stock.report_delivery_document" primary="True">
Isn't better to overwrite standard report with this one?

2017-02-23 17:02 UTC, carlosdauden commented on stock_picking_report_custom_description/i18n/es.po
> +msgstr "Operaciones de picking (descripción)"
This Is the same translation of original report name

2017-02-23 17:05 UTC, carlosdauden commented on stock_picking_report_custom_description/views/report_deliveryslip.xml
> +    <template id="report_delivery_document_description" inherit_id="stock.report_delivery_document" primary="True">
In this way we have more flexibility at no cost

2017-02-23 17:07 UTC, carlosdauden commented
I think it does serve:
https://github.com/OCA/stock-logistics-reporting/pull/32/files#diff-2b79a6178ed01a822c4c4f1fa17bdc9eR25

2017-05-16 15:48 UTC, MiquelRForgeFlow requested changes

2017-05-16 15:48 UTC, mreficent commented on stock_picking_report_custom_description/README.rst
> +
Please, could you add <code>Usage</code> section?

2017-08-30 19:17 UTC, pedrobaeza commented on stock_picking_report_custom_description/i18n/es.po
> +msgstr "Operaciones de picking (descripción)"
Original translation is incorrect then :wink:

2019-01-29 15:33 UTC, closed without merging