[ADD] [16.0] stock_picking_report_delivery_driver
OCA/stock-logistics-reporting pull request #321
Opened 2024-05-29 09:58 UTC by Shide

Adds Delivery Driver to Stock Picking reports

## Delivery Slip report
![image](https://github.com/OCA/stock-logistics-reporting/assets/1162050/85fbebfb-aadb-4a6e-9fc1-65a195b377cb)

## Picking Operations report
![image](https://github.com/OCA/stock-logistics-reporting/assets/1162050/0888ae92-1d3f-483f-8e50-bf77cb933c83)

## Delivery Slip without Carrier but Driver
![image](https://github.com/OCA/stock-logistics-reporting/assets/1162050/96a6939d-246c-4734-9b0c-09c255de9097)

MT-6115 @moduon  @rafaelbn @yajo @EmilioPascual @fcvalgar please review if you want :)

2024-05-29 13:37 UTC, fcvalgar approved these changes
Functional review.

LGTM, Thank you @Shide 

![image](https://github.com/OCA/stock-logistics-reporting/assets/17847432/d906436e-dc0f-4301-82da-2fa2d0594f6c)

Picking Operations 
![image](https://github.com/OCA/stock-logistics-reporting/assets/17847432/b5624e2c-f583-4c1d-9ec4-9f0f6dbb47e9)

Delivery Slip
![image](https://github.com/OCA/stock-logistics-reporting/assets/17847432/301c1cb9-a838-420d-b386-1ee445d005d3)

Only driver
![image](https://github.com/OCA/stock-logistics-reporting/assets/17847432/a49dedf1-afe9-4752-b3ae-8a711441210e)

Only Carrier
![image](https://github.com/OCA/stock-logistics-reporting/assets/17847432/34f4d9d8-0d04-49d4-99f7-7d1fa46cfff6)

2024-05-30 11:19 UTC, EmilioPascual requested changes
Nice Job @Shide. Just a single change

2024-05-30 11:19 UTC, EmilioPascual commented on stock_picking_report_delivery_driver/__manifest__.py
> +    "maintainers": ["Shide"],
```suggestion
    "maintainers": ["Shide", "rafaelbn"],
```

2024-05-31 09:21 UTC, yajo requested changes

2024-05-31 09:21 UTC, yajo commented on stock_picking_report_delivery_driver/report/report_deliveryslip.xml
> +                <span t-if="o.carrier_id">)</span>
Avoid unneeded whitespace on reports:

```suggestion
                <span t-if="o.carrier_id">(</span><span t-field="o.driver_id.name" /><span t-if="o.carrier_id">)</span>
```

2024-05-31 09:21 UTC, yajo commented on stock_picking_report_delivery_driver/report/report_stockpicking_operations.xml
> +                <span t-if="o.carrier_id">)</span>
```suggestion
                <span t-if="o.carrier_id">(</span><span t-field="o.driver_id.name" /><span t-if="o.carrier_id">)</span>
```

2024-05-31 11:31 UTC, EmilioPascual approved these changes

2024-06-02 20:46 UTC, rafaelbn approved these changes
👍🏼 Thank you!

2024-06-02 20:46 UTC, rafaelbn commented
/ocabot merge patch

2024-06-02 20:55 UTC, rafaelbn commented
/ocabot merge nobump

2024-06-02 21:37 UTC, rafaelbn commented
Hello @Shide ! :-)

Test are failing, this is the message:
```

2024-06-02 20:58:05,334 288 ERROR odoo odoo.addons.stock_average_daily_sale.tests.test_average_daily_sale: FAIL: TestAverageSale.test_average_sale
Traceback (most recent call last):
  File "/__w/stock-logistics-reporting/stock-logistics-reporting/stock_average_daily_sale/tests/test_average_daily_sale.py", line 52, in test_average_sale
    self.assertRecordValues(
  File "/opt/odoo/odoo/tests/common.py", line 610, in assertRecordValues
    self.fail('\n'.join(errors))
AssertionError: The records and expected_values do not match.
Wrong number of records to compare: 0 records versus 1 expected values.

==== Missing record ====
{'average_qty_by_sale': 10.0,
 'nbr_sales': 1.0,
 'qty_in_stock': 40.0,
 'recommended_qty': 20.0,
 'warehouse_id': 1}
 
2024-06-02 20:58:05,337 288 INFO odoo odoo.addons.stock_average_daily_sale.tests.test_average_daily_sale: Starting TestAverageSale.test_average_sale_multiple ... 
2024-06-02 20:58:05,631 288 INFO odoo odoo.addons.stock_average_daily_sale.tests.test_average_daily_sale: ====================================================================== 
2024-06-02 20:58:05,631 288 ERROR odoo odoo.addons.stock_average_daily_sale.tests.test_average_daily_sale: FAIL: TestAverageSale.test_average_sale_multiple
Traceback (most recent call last):
  File "/__w/stock-logistics-reporting/stock-logistics-reporting/stock_average_daily_sale/tests/test_average_daily_sale.py", line 129, in test_average_sale_multiple
    self.assertRecordValues(
  File "/opt/odoo/odoo/tests/common.py", line 610, in assertRecordValues
    self.fail('\n'.join(errors))
AssertionError: The records and expected_values do not match.
Wrong number of records to compare: 0 records versus 1 expected values.

==== Missing record ====
{'nbr_sales': 3.0, 'qty_in_stock': 19.0, 'warehouse_id': 1}
```

2024-06-04 09:23 UTC, Shide commented
@rousseldenis @lmignon Could you please check the failing tests in `stock_average_daily_sale` module?

2024-06-04 10:16 UTC, rousseldenis commented
> @rousseldenis @lmignon Could you please check the failing tests in `stock_average_daily_sale` module?

@Shide Where ?

2024-06-04 10:17 UTC, rousseldenis commented
> > @rousseldenis @lmignon Could you please check the failing tests in `stock_average_daily_sale` module?
> 
> @Shide Where ?

Ok, I see. I can check

2024-06-04 11:38 UTC, rousseldenis commented
/ocabot merge nobump

2024-06-04 11:44 UTC, merged

2024-06-05 05:40 UTC, Shide commented
@rousseldenis what was happening? What do you do to let tests pass?

2024-06-05 06:34 UTC, rousseldenis commented
> @rousseldenis what was happening? What do you do to let tests pass?

Apparently, a temporary failure. Wasn't able to reproduce problem locally, I re run the merge