[14.0][ADD] auto_printing_stock_picking
OCA/stock-logistics-reporting pull request #354
Opened 2024-12-06 12:25 UTC by jbaudoux

When a picking is done, automatically trigger the printing of some documents.
This can be used to print a delivery slip (report) or labels received from the carrier (attachment).

Depends on:
* https://github.com/OCA/report-print-send/pull/310

2024-12-06 13:41 UTC, jbaudoux commented
cc @mt-software-de @sebalix

2024-12-06 13:45 UTC, mt-software-de approved these changes
LGTM

2024-12-06 14:05 UTC, simahawk reviewed
LG

2025-01-22 15:26 UTC, jbaudoux commented on printing_auto_stock_picking/models/stock_picking_type.py
> +        domain=[("model", "=", "stock.picking.type")],
@mt-software-de I wonder if this is not a mistake and if we should not put the model of what is printed instead of where it is configured? And in `_get_printing_auto` filter on that model. https://github.com/OCA/report-print-send/pull/310/files#diff-1360f4baf5029947c074c2576244e65952f4043906416d240f5026996ac26f68R37

2025-01-22 17:44 UTC, mt-software-de commented on printing_auto_stock_picking/models/stock_picking_type.py
> +        domain=[("model", "=", "stock.picking.type")],
Maybe I don't quite understand what you mean.
We need to configure the printing.auto on the picking.type.
I also think we should change the model in the domain to stock.picking. This then aligned with the model which is printing. 
But a filter is not needed, because the auto_printing_ids are on the model with the mixin.

2025-05-25 13:01 UTC, mt-software-de requested changes

2025-05-25 13:01 UTC, mt-software-de commented on printing_auto_stock_picking/views/stock_picking_type.xml
> +                    context="{'default_model': 'stock.picking.type'}"
Could you also Change The model here?
```suggestion
                    context="{'default_model': 'stock.picking'}"
```

2025-05-25 13:01 UTC, mt-software-de commented on printing_auto_stock_picking/models/stock_picking_type.py
> +        domain=[("model", "=", "stock.picking.type")],
Yes we should change the Domain to `stock.picking` this makes more sense. And change it on the view and it should be fine

2025-07-09 13:03 UTC, jbaudoux commented on printing_auto_stock_picking/models/stock_picking_type.py
> +        domain=[("model", "=", "stock.picking.type")],
fixed in https://github.com/OCA/stock-logistics-reporting/pull/354/commits/c137eb423f6daaf07c928cacd13f2eac79f2c9f8

2025-07-09 13:05 UTC, jbaudoux commented
@mt-software-de I fixed the model and added a migration script

2025-07-09 14:03 UTC, mt-software-de approved these changes
LGTM

2025-07-09 14:05 UTC, jbaudoux commented
/ocabot merge nobump

2025-07-09 14:11 UTC, merged