[11.0] [mig] stock_picking_report_custom_description
OCA/stock-logistics-reporting pull request #45
Opened 2018-09-25 16:29 UTC by sergio-teruel

cc @Tecnativa

2018-09-25 19:05 UTC, pedrobaeza requested changes
Remove from root `__init__.py` the import of models folder.

I'm missing the view in backend UI of the `name` field in both "Operations" and "Detailed operations".

2018-09-25 19:05 UTC, pedrobaeza commented on stock_picking_report_custom_description/readme/USAGE.rst
> +#. Create a sale order and set manual descriprion in sale order lines.
s/descriprion/description

2018-09-25 19:05 UTC, pedrobaeza commented
You can also squash a bit commit history

2018-09-26 08:45 UTC, tafaRU requested changes
@sergio-teruel please note that Travis failed due to https://travis-ci.org/OCA/stock-logistics-reporting/jobs/433041027#L1285 beacause of https://github.com/Tecnativa/stock-logistics-reporting/blob/11.0-mig-stock_picking_report_custom_description/stock_picking_report_custom_description/__init__.py#L2

2018-09-30 08:11 UTC, bodedra commented on stock_picking_report_custom_description/__manifest__.py
> +    "website": "https://www.tecnativa.com",
Shouldn't be https://github.com/OCA/stock-logistics-reporting ?

2018-09-30 08:11 UTC, bodedra commented on stock_picking_report_custom_description/views/report_deliveryslip.xml
> +<?xml version="1.0" encoding="UTF-8" ?>
Please remove `encoding="UTF-8"`

2018-09-30 08:12 UTC, bodedra commented on stock_picking_report_custom_description/views/report_stockpicking_operations.xml
> +<?xml version="1.0" encoding="utf-8"?>
Same here. Remove `encoding="UTF-8"`

2018-09-30 08:12 UTC, bodedra commented on stock_picking_report_custom_description/views/stock_report.xml
> +<?xml version="1.0" encoding="utf-8"?>
Same as above

2018-10-01 08:36 UTC, pedrobaeza commented
@sergio-teruel can you please finish this?

2018-11-27 17:19 UTC, pedrobaeza approved these changes

2018-11-27 17:19 UTC, pedrobaeza commented
@tafaRU @bodedra  everything attended.

2018-11-28 04:15 UTC, bodedra approved these changes
Code Review :+1:

2018-11-28 08:32 UTC, tafaRU approved these changes
Both functional and technical :+1:

2018-11-28 08:33 UTC, merged