[12.0][ADD] stock_picking_product_label
OCA/stock-logistics-reporting pull request #79
Opened 2019-11-12 12:52 UTC by NuriaMartinXifre

New module that allows printing labels of all products in a stock picking.

cc ~ @Eficent

2019-11-12 15:50 UTC, NuriaMartinXifre commented
Runbot error is not related

2019-11-15 08:02 UTC, JoanSForgeFlow approved these changes
Functional review done!

2019-11-25 22:03 UTC, rousseldenis requested changes
Little change

2019-11-25 22:03 UTC, rousseldenis commented on stock_picking_product_label/__manifest__.py
> +    'category': 'Customer Relationship Management',
Change this to 'Warehouse' as it will appear in the wrong category in OCA shop

2019-11-27 12:44 UTC, HviorForgeFlow reviewed
Minor comments about styling. Code review LGTM

2019-11-27 12:44 UTC, hveficent commented on stock_picking_product_label/__manifest__.py
> +# Copyright 2019 Eficent <patrickraymondwilson@gmail.com>
```suggestion
# Copyright 2019 Eficent Business and IT Consulting Services S.L.
```

2019-11-27 12:44 UTC, hveficent commented on stock_picking_product_label/readme/CONTRIBUTORS.rst
> +
Drop one line,
Last line must be empty.

2019-11-27 12:44 UTC, hveficent commented on stock_picking_product_label/readme/DESCRIPTION.rst
> +
Drop lines

2020-01-29 03:08 UTC, ps-tubtim reviewed
Function test: OK. Minor comment about code.

2020-01-29 03:08 UTC, ps-tubtim commented on stock_picking_product_label/reports/report_print_labels.xml
> +    <data>
`<data>` and `</data>` are unnecessary in v.12

2020-02-25 07:10 UTC, ps-tubtim reviewed
I think <data> and </data> are unnecessary in v.12

2020-02-25 07:10 UTC, ps-tubtim commented on stock_picking_product_label/reports/report_print_labels_template.xml
> +    <data>
```suggestion
```

2020-02-25 07:10 UTC, ps-tubtim commented on stock_picking_product_label/reports/report_print_labels_template.xml
> +     </data>
```suggestion
```

2020-02-26 02:27 UTC, ps-tubtim approved these changes

2020-02-27 11:32 UTC, MiquelRForgeFlow approved these changes

2020-03-02 16:01 UTC, LoisRForgeFlow approved these changes
Code review :+1:

2020-03-02 16:02 UTC, LoisRForgeFlow commented
All review attended, thanks @NuriaMForgeFlow!

/ocabot merge

2020-03-02 16:16 UTC, merged